default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chores_backend_development


test:
  <<: *default
  database: chores_backend_test

production:
  <<: *default
  database: chores_backend_production
  username: postgres
  password: <%= Rails.application.credentials.postgres.dig(:password) %>
